### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [QMAST/SailCode2017#5]
In the file "SailCode2017/Arduino/QMAST_Main/Sensors.ino" the waiting after a Wire.requestFrom() with `while (Wire.available() < 2);` can be removed.

Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by angelolu** [comment]
Thank you for the heads up! We have made changes in the latest commit to master.

**Comment by Koepel** [comment]
Hi, is there another master that I don't know of ? Because the `while (Wire.available() < 2);` are still there.
